name: MushrimHG
version: 1.0
main: me.mushrim.hg.Main
author: Harium
description: Um plugin de Hunger Games para Spigot 1.8.9
commands:
  hg:
    description: Comando principal do HG
    usage: /hg [start|stop|setlobby|setspawn]
  starthg:
    description: Inicia o jogo
    usage: /starthg